Vagrant.configure("2") do |config|
  
 # config.vm.box = "ktr/mininet"
  config.ssh.insert_key = false
  config.vbguest.auto_update = false
# -------- CLIENTE 1 --------
  config.vm.define "cliente1" do |c1|
    c1.vm.box = "ubuntu/trusty64"
    c1.vm.hostname = "cliente1"
    c1.vm.network "private_network", ip: "192.168.56.11"

    c1.vm.provider "virtualbox" do |vb|
      vb.name = "cliente1"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.memory = "256"
    end #do vb
  end #do client_config

  # config.vm.box = "ktr/mininet"
  # -------- CLIENTE 2 --------
  config.vm.define "cliente2" do |c2|
    c2.vm.box = "ubuntu/trusty64"
    c2.vm.hostname = "cliente2"
    c2.vm.network "private_network", ip: "192.168.56.12"

    c2.vm.provider "virtualbox" do |vb|
      vb.name = "cliente2"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.memory = "256"
    end #do vb
  end #do client_config

  # config.vm.box = "ktr/mininet" 
   config.vm.define "webserver" do |web_config| 
    web_config.vm.box = "ubuntu/trusty64" 
    web_config.vm.hostname = "webserver" 
    web_config.vm.network  "private_network", ip: "192.168.56.21" 
    web_config.vm.network  "forwarded_port", guest: 80, host: 8080 
    web_config.vm.provider "virtualbox" do |vb|
       vb.name = "webserver" 
       opts = ["modifyvm", :id, "--natdnshostresolver1", "on"] 
       vb.customize opts 
       vb.memory = "256" 
      end #do vb
      web_config.vm.provision "shell", path: "bootstrap_web.sh" 
    end #do web_config 
  end #do config

  